-- CreateEnum
CREATE TYPE "DmType" AS ENUM ('AI', 'HUMAN');

-- CreateEnum
CREATE TYPE "SenderRole" AS ENUM ('USER', 'AI_DM', 'HUMAN_DM', 'SYSTEM');

-- CreateEnum
CREATE TYPE "SessionStatus" AS ENUM ('PLANNED', 'ACTIVE', 'FINISHED');

-- CreateTable
CREATE TABLE "PUBLIC_USER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PUBLIC_USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CAMPAIGN" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT NOT NULL,
    "description" TEXT,
    "inviteCode" UUID,
    "systemBase" TEXT NOT NULL,
    "dmType" "DmType" NOT NULL,
    "creatorId" UUID NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PUBLIC_CAMPAIGN_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CAMPAIGN_MEMBER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "userId" UUID NOT NULL,
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_CAMPAIGN_MEMBER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CHARACTER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "level" INTEGER NOT NULL DEFAULT 1,
    "hpCurrent" INTEGER NOT NULL,
    "hpMax" INTEGER NOT NULL,
    "isBot" BOOLEAN NOT NULL DEFAULT false,
    "botType" TEXT,
    "avatarUrl" TEXT,
    "attributes" JSONB NOT NULL DEFAULT '{}',
    "isAlive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "userId" UUID NOT NULL,
    "campaignId" UUID NOT NULL,
    "raceId" UUID NOT NULL,
    "classId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_CHARACTER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_RACE" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "traits" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "PUBLIC_RACE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CLASS" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT,
    "hitDice" TEXT NOT NULL,

    CONSTRAINT "PUBLIC_CLASS_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CHARACTER_ITEM" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "characterId" UUID NOT NULL,
    "itemId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_CHARACTER_ITEM_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_CHARACTER_SPELL" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "characterId" UUID NOT NULL,
    "spellId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_CHARACTER_SPELL_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_ITEM_TEMPLATE" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "description" TEXT,
    "properties" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "PUBLIC_ITEM_TEMPLATE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_SPELL_TEMPLATE" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "level" INTEGER NOT NULL,
    "school" TEXT,
    "castingTime" TEXT,
    "range" TEXT,
    "duration" TEXT,
    "description" TEXT,
    "damage" JSONB,

    CONSTRAINT "PUBLIC_SPELL_TEMPLATE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_MONSTER_TEMPLATE" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "challenge" DOUBLE PRECISION NOT NULL,
    "armorClass" INTEGER NOT NULL,
    "hitPoints" INTEGER NOT NULL,
    "stats" JSONB NOT NULL DEFAULT '{}',
    "actions" JSONB NOT NULL DEFAULT '{}',

    CONSTRAINT "PUBLIC_MONSTER_TEMPLATE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_MONSTER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "characterId" UUID,
    "monsterTemplateId" UUID NOT NULL,
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_MONSTER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_MESSAGE" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "content" TEXT NOT NULL,
    "senderId" UUID NOT NULL,
    "diceRoll" JSONB,
    "isWhisper" BOOLEAN NOT NULL DEFAULT false,
    "senderRole" "SenderRole",
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_MESSAGE_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_SESSION" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" TEXT,
    "scheduledFor" TIMESTAMP(3),
    "status" "SessionStatus" NOT NULL,
    "summary" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_SESSION_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_COMBAT_ENCOUNTER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "isActive" BOOLEAN NOT NULL DEFAULT false,
    "round" INTEGER NOT NULL DEFAULT 1,
    "turnOrder" JSONB NOT NULL DEFAULT '{}',
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_COMBAT_ENCOUNTER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_MAP" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "imageUrl" TEXT NOT NULL,
    "gridConfig" JSONB NOT NULL DEFAULT '{}',
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_MAP_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PUBLIC_PLAYER_CHARACTER" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "userId" UUID NOT NULL,
    "campaignId" UUID NOT NULL,

    CONSTRAINT "PUBLIC_PLAYER_CHARACTER_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "PUBLIC_USER_email_key" ON "PUBLIC_USER"("email");

-- CreateIndex
CREATE UNIQUE INDEX "PUBLIC_CAMPAIGN_inviteCode_key" ON "PUBLIC_CAMPAIGN"("inviteCode");

-- CreateIndex
CREATE UNIQUE INDEX "PUBLIC_CAMPAIGN_MEMBER_userId_campaignId_key" ON "PUBLIC_CAMPAIGN_MEMBER"("userId", "campaignId");

-- AddForeignKey
ALTER TABLE "PUBLIC_CAMPAIGN" ADD CONSTRAINT "PUBLIC_CAMPAIGN_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "PUBLIC_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CAMPAIGN_MEMBER" ADD CONSTRAINT "PUBLIC_CAMPAIGN_MEMBER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "PUBLIC_USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CAMPAIGN_MEMBER" ADD CONSTRAINT "PUBLIC_CAMPAIGN_MEMBER_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER" ADD CONSTRAINT "PUBLIC_CHARACTER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "PUBLIC_USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER" ADD CONSTRAINT "PUBLIC_CHARACTER_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER" ADD CONSTRAINT "PUBLIC_CHARACTER_raceId_fkey" FOREIGN KEY ("raceId") REFERENCES "PUBLIC_RACE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER" ADD CONSTRAINT "PUBLIC_CHARACTER_classId_fkey" FOREIGN KEY ("classId") REFERENCES "PUBLIC_CLASS"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER_ITEM" ADD CONSTRAINT "PUBLIC_CHARACTER_ITEM_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "PUBLIC_CHARACTER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER_ITEM" ADD CONSTRAINT "PUBLIC_CHARACTER_ITEM_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "PUBLIC_ITEM_TEMPLATE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER_SPELL" ADD CONSTRAINT "PUBLIC_CHARACTER_SPELL_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "PUBLIC_CHARACTER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_CHARACTER_SPELL" ADD CONSTRAINT "PUBLIC_CHARACTER_SPELL_spellId_fkey" FOREIGN KEY ("spellId") REFERENCES "PUBLIC_SPELL_TEMPLATE"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MONSTER" ADD CONSTRAINT "PUBLIC_MONSTER_characterId_fkey" FOREIGN KEY ("characterId") REFERENCES "PUBLIC_CHARACTER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MONSTER" ADD CONSTRAINT "PUBLIC_MONSTER_monsterTemplateId_fkey" FOREIGN KEY ("monsterTemplateId") REFERENCES "PUBLIC_MONSTER_TEMPLATE"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MONSTER" ADD CONSTRAINT "PUBLIC_MONSTER_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MESSAGE" ADD CONSTRAINT "PUBLIC_MESSAGE_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "PUBLIC_USER"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MESSAGE" ADD CONSTRAINT "PUBLIC_MESSAGE_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_SESSION" ADD CONSTRAINT "PUBLIC_SESSION_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_COMBAT_ENCOUNTER" ADD CONSTRAINT "PUBLIC_COMBAT_ENCOUNTER_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_MAP" ADD CONSTRAINT "PUBLIC_MAP_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_PLAYER_CHARACTER" ADD CONSTRAINT "PUBLIC_PLAYER_CHARACTER_userId_fkey" FOREIGN KEY ("userId") REFERENCES "PUBLIC_USER"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PUBLIC_PLAYER_CHARACTER" ADD CONSTRAINT "PUBLIC_PLAYER_CHARACTER_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "PUBLIC_CAMPAIGN"("id") ON DELETE CASCADE ON UPDATE CASCADE;
